"""
Patterns for helping with regexing of entries
"""
# -*- coding: utf-8 -*-

IN_PARENTHESIS = [
    "growing of vegetables, cereals and plants",
    "growing of cereals, crops and vegetables",
    "not currently trading",
    "and related companies",
    "investment vehicle",
    "interest ceased",
    "biotechnology",
    "see category",
    "real estate",
    "liquidation",
    "non-trading",
    "not trading",
    "formerly",
    "property",
    "dormant",
]

POSITIONS = [
    "Non-executive Director and Chair of the Audit and Risk & Compliance Committees",
    "Non-executive Director and Senior Independent Director",
    "Founder, Beneficial Owner and Non-executive Chairman",
    "Non-executive Chairman and Non-executive Director",
    "Non-executive Director and Chair of Remuneration",
    "Non-executive Director and Chairman Designate",
    "Non-executive Director and Strategic Adviser",
    "Non-executive Director and Member of Board",
    "Member of Global Board of Representatives",
    "Self-employed consultant and sole trader",
    "Self-employed consultant and sole trader",
    "Non-executive Director and Deputy Chair",
    "Co-founder and Executive Chairperson",
    "Member, General Management Committee",
    "Non-executive Director and Chairman",
    "Chairman and Non-executive Director",
    "Chairman and non-executive Director",
    "Non-executive Chairman and Director",
    "Chairman of Directors, and Director",
    "Independent Non-executive Director",
    "Director and Chairman of the Board",
    "Chairman of the Board and Director",
    "Director and Chairman of the Board",
    "Non-executive Member of the Board",
    "Non-executive Director and Chair",
    "Chair and non-executive director",
    "Non-executive Director and Chair",
    "Director and Non-executive Chair",
    "Founder and Controlling Director",
    "Executive Chairman and Director",
    "Sole Owner, Executive Chairman",
    "Director and Chair of Advisers",
    "Chairman and Managing Director",
    "Independent National Director",
    "Non-executive Deputy Chairman",
    "Chairman, Board of Directors",
    "Deputy Chair and Trustee of",
    "Senior Independent Director",
    "Non-executive Board Member",
    "Director and sole owner",
    "Chief Executive Officer",
    "Non-executive Director",
    "Non-executive Director",
    "Member, Advisory Board",
    "Non-executive Chairman",
    "Chairman and Director",
    "Director and Chairman",
    "Director and Chairman",
    "Chairman and Director",
    "Chairman and Director",
    "Director and Trustee",
    "Chairman and Founder",
    "Non-executive Chair",
    "Member of the Board",
    "Executive President",
    "Director & Chairman",
    "Chairman & Director",
    "Executive Chairman",
    "Board of Directors",
    "Supervisory Board",
    "Managing Director",
    "Deputy Chairman",
    "Member of Board",
    "Chairman Elect",
    "Director/Owner",
    "Board Director",
    "Vice Chairman",
    "Board Member",
    "Sole Owner",
    "President",
    "Director",
    "Trustee,",
    "Chairman",
    "Chair of",
    "Partner",
    "Member",
    "Chair",
    "CEO",
    "director and sole shareholder",
    "Director and shareholder",
    "Co-Chair",
    "unremunerated director",
    "Vice",
    "vice",
    "officer",
    "Ambassador",
    "ambassador",
    "Life Governor",
    "Governor",
    "Consultant",
    "Chancellor",
    "Fellow",
    "Chair of the Trustees",
    "a trustee",
    "member of the Board",
    "Vice President",
    "Unremunerated director",
    "Adviser",
    "Honorary Associate",
    "Honorary",
    "Honorary Vice President",
    "unremunerated",
    "Advisory",
    "advisor",
    "Chair of Governors",
    "Member-at-large",
    "editor",
    "Steward",
    "Visiting Professor",
    "Council Member",
    "Advisory Board",
    "Commissioner",
    "Committee Member",
    "Member of the Panel",
    "Association Member",
    "Vice Chair",
    "Trust Member",
    "Non-executive Chairperson",
    "Strategic Adviser",
    "General Partner",
    "Advisory Council",
    "Professor Emeritus",
    "Elder",
    "Lords Chair",
    "Honorary Bencher",
    "Advisory Board",
    "Joint President",
    "Master of the Horse",
    "Chair of Governing Body",
    "Chairman of the Board",
    "Visiting Parliamentary Fellow",
    "Council of Reference Member",
    "Senior Associate Fellow",
    "Bencher",
    "International Council Member",
    "Independent Member",
    "Commissary",
    "Visiting Professor and Distinguished Visitor (with certain benefits)",
    "Foundation Governor",
    "Gorsedd of Bards",
    "Honorary Captain",
    "Warden and Governor",
    "Senior Partner",
]
