"""
Patterns for helping with regexing of entries
"""
# -*- coding: utf-8 -*-

IN_PARENTHESIS = [
    "growing of vegetables, cereals and plants",
    "growing of cereals, crops and vegetables",
    "not currently trading",
    "and related companies",
    "investment vehicle",
    "interest ceased",
    "biotechnology",
    "see category",
    "real estate",
    "liquidation",
    "non-trading",
    "not trading",
    "formerly",
    "property",
    "dormant",
]

POSITIONS = [
    "Non-executive Director and Chair of the Audit and Risk & Compliance Committees",
    "Non-executive Director and Senior Independent Director",
    "Founder, Beneficial Owner and Non-executive Chairman",
    "Non-executive Chairman and Non-executive Director",
    "Non-executive Director and Chair of Remuneration",
    "Non-executive Director and Chairman Designate",
    "Non-executive Director and Strategic Adviser",
    "Non-executive Director and Member of Board",
    "Member of Global Board of Representatives",
    "Self-employed consultant and sole trader",
    "Self-employed consultant and sole trader",
    "Non-executive Director and Deputy Chair",
    "Co-founder and Executive Chairperson",
    "Member, General Management Committee",
    "Non-executive Director and Chairman",
    "Chairman and Non-executive Director",
    "Chairman and non-executive Director",
    "Non-executive Chairman and Director",
    "Chairman of Directors, and Director",
    "Independent Non-executive Director",
    "Director and Chairman of the Board",
    "Chairman of the Board and Director",
    "Director and Chairman of the Board",
    "Non-executive Member of the Board",
    "Non-executive Director and Chair",
    "Chair and non-executive director",
    "Non-executive Director and Chair",
    "Director and Non-executive Chair",
    "Founder and Controlling Director",
    "Executive Chairman and Director",
    "Sole Owner, Executive Chairman",
    "Director and Chair of Advisers",
    "Chairman and Managing Director",
    "Independent National Director",
    "Non-executive Deputy Chairman",
    "Chairman, Board of Directors",
    "Deputy Chair and Trustee of",
    "Senior Independent Director",
    "Non-executive Board Member",
    "Director and sole owner",
    "Chief Executive Officer",
    "Non-executive Director",
    "Non-executive Director",
    "Member, Advisory Board",
    "Non-executive Chairman",
    "Chairman and Director",
    "Director and Chairman",
    "Director and Chairman",
    "Chairman and Director",
    "Chairman and Director",
    "Director and Trustee",
    "Chairman and Founder",
    "Non-executive Chair",
    "Member of the Board",
    "Executive President",
    "Director & Chairman",
    "Chairman & Director",
    "Executive Chairman",
    "Board of Directors",
    "Supervisory Board",
    "Managing Director",
    "Deputy Chairman",
    "Member of Board",
    "Chairman Elect",
    "Director/Owner",
    "Board Director",
    "Vice Chairman",
    "Board Member",
    "Sole Owner",
    "President",
    "Director",
    "Trustee,",
    "Chairman",
    "Chair of",
    "Partner",
    "Member",
    "Chair",
    "CEO",
    "director and sole shareholder",
    "Director and shareholder",
    "Co-Chair",
    "unremunerated director",
    "Vice",
    "vice",
    "officer",
    "Ambassador",
    "ambassador",
    "Life Governor",
    "Governor",
    "Consultant",
    "Chancellor",
    "Fellow",
    "Chair of the Trustees",
    "a trustee",
    "member of the Board",
    "Vice President",
    "Unremunerated director",
    "Adviser",
    "Honorary Associate",
    "Honorary",
    "Honorary Vice President",
    "unremunerated",
    "Advisory",
    "advisor",
    "Chair of Governors",
    "Member-at-large",
    "editor",
    "Steward",
    "Visiting Professor",
    "Council Member",
    "Advisory Board",
    "Commissioner",
    "Committee Member",
    "Member of the Panel",
    "Association Member",
    "Vice Chair",
    "Trust Member",
    "Non-executive Chairperson",
    "Strategic Adviser",
    "General Partner",
    "Advisory Council",
    "Professor Emeritus",
    "Elder",
    "Lords Chair",
    "Honorary Bencher",
    "Advisory Board",
    "Joint President",
    "Master of the Horse",
    "Chair of Governing Body",
    "Chairman of the Board",
    "Visiting Parliamentary Fellow",
    "Council of Reference Member",
    "Senior Associate Fellow",
    "Bencher",
    "International Council Member",
    "Independent Member",
    "Commissary",
    "Visiting Professor and Distinguished Visitor (with certain benefits)",
    "Foundation Governor",
    "Gorsedd of Bards",
    "Honorary Captain",
    "Warden and Governor",
    "Senior Partner",
    "Pro Vice Chancellor",
    "Columnist",
    "Advisory Group",
    "Trust Protector",
    "Visitor",
    "Supporter",
    "Shareholder",
    "Member of Council",
    "Member of Court (Trustee)",
    "Episcopal",
    "Elector",
    "Dual President",
    "Board of Trustees",
    "Vice-President",
    "Church Leader",
    "Chair of Council",
    "Development Committee Member",
    "Chairman of Trustees",
    "Trustee and Director",
    "Member, Advisory Panel",
    "Senior Adviser to the Group Executive Chairman",
    "International Chairman Emeritus",
    "Vice Patron",
    "Friend",
    "President Emeritus (formerly Vice President)",
    "Editorial Adviser" "Co-Chairman",
    "Founding",
    "Founding Chairman",
    "Founding Member",
    "Champion",
    "International Envoy",
    "Co-founder",
    "Honorary Group Captain",
    "Founder Freeman",
    "Chairman of the Executive",
    "Executive Member",
    "Emeritus Professor",
    "Paul Hamlyn Chair",
    "Elected Member",
    "Member of Governing Body",
    "Advice on sustainability and planning to",
    "Co-founder",
    "Co-owner and Chairman of Advisory Board",
]

RECURRING_INDICATORS = [
    "opinion surveys ",
    "payments received for articles ",
    "for columns ",
    "payment from ",
    "fees received ",
    "payments received via ",
    "registered nurse at ",
    "payments received through via ",
    "payments for articles ",
    "fees for completing surveys ",
    "payments from ",
    "payments received from ",
    "fees from ",
    "payments for speeches received ",
    "payments received for my ",
    "solicitor ",
    "partner in somerset ",
    "cell therapy ltd ",
    "partner, gatley farms",
    "gulf keystone petroleum",
    "councillor",
    "freelance gp ",
    "contracted to provide legal consultancy",
    "partner in east beckham",
    "political consultant (ad hoc)",
    "for one semester",
    "payments received by",
    "surgeon commander",
    "lecturer at",
    "wandsworth council",
    "chairman of investment committee of charles stanley",
    "payments from head of zeus",
    "Position on the Advisory Board of",
    "William Cash & Co",
    "adviser to TLG Capital",
    "senior adviser to Montrose",
    "for completing opinion surveys",
    "managing director of",
    "partner in Bendles",
    "part time salaried General Practitioner",
    "Partner in East Beckham partnership",
    "political consultant (ad hoc) for the Confederation",
    "Lay Associate Member of the Medical Practitioners Tribunal Service",
    "Any additional payments are listed below",
    "Locum Consultant",
    "work as an NHS doctor",
    "Consultancy fees received",
    "Chair of Optimised Waste Logistics Group",
    "political consultant",
    "In addition to the remuneration detailed below",
    "payments from the sun",
    "Accloud Plc",
    "Nicholas Woolf and Co",
    "Mansfeider Kupfer Und Messing",
    "Payments for articles",
    "Consultant on political and policy risk to Venn & Partners LLP",
    "Senior Adviser giving strategic advice to Brennan and Partners Ltd",
    "Columnist",
    "Payments received:",
    "Head of Strategy for",
    "received for consultancy",
    "Payments for legal advice",
    "payments received as",
    "Payments for work as",
    "weekly column for",
    "Until further notice, I will receive",
    "for work as an external adviser",
    "Consultancy fees received",
    "final payments for which",
    "external advisor to JCB",
    "for services as a director",
    "Until further notice",
    "2023-28 regulatory period",
    "for legal services",
    "in 2020-21",
]

SINGLE_INDICATORS = [
    "advice provided",
    "in respect of ",
    "drawing",
    "received ",
    " I drew ",
    " payment ",
    "for interview ",
    "fee of ",
    "drawings",
    "in royalties ",
    "received advance ",
    "received royalties ",
    "expected for ",
    "paid direct to community group",
    "payment of ",
    "payment received ",
    "payments for",
    "article",
    "articles",
    "survey",
    "surveys",
    " v ",
    "appearances",
    "was paid to a family member",
    "received a redundancy payment",
    "receive an annual allowance of",
    "received additional sum of",
    "Until further notice I receive",
    "Until further notice, I receive",
    "received final payment",
    "to meet tax liability",
    "I drew",
    "until further notice I expect",
    "Until further notice, I will receive",
    "for a survey",
    "I shall receive fees",
    "received final payment of",
    "for a survey completed",
    "for consultancy work",
    "royalties of",
    "expected for a survey",
]

# constitutional state powers indentifiers
CROWN_IDENTIFIERS = [
    "The Crown",
    "The Queen",
    "HM The Queen",
    "Queen's Bodyguard",
]

JURDICARY_IDENTIFIERS = [
    "Bench",
    "The Bar",
]

CHURCH_OF_ENGLAND_IDENTIFIERS = [
    "Church Council",
    "Mucknell Abbey",
    "Malling Abbey",
    "Archbishop of Canterbury’s Examination in Theology",
    "episcopal stipend",
    "Episcopal",
    "Anglican",
    "Ecclesiastical",
    "Evangelists",
    "Preachers",
    "church pension",
]

ARMED_FORCES_IDENTIFIERS = [
    "reservist",
    "reserve army",
    "territorial army",
    "TA Regiment",
    "Colonel Commandant",
    "601 Squadron",
]

GOVERNMENT_IDENTIFIERS = [
    "Lieutenant of",
    "Lord-Lieutenant",
    "Her Majesty's Government",
    "Government Whip",
    "Leader of the House of Lords",
    "Lord Privy Seal",
    "Special Envoy",
    "Trade Envoy",
]

LOCAL_GOVERNMENT_IDENTIFIERS = ["council", "borough"]

STATE_POWERS_IDENTIFIERS = (
    CROWN_IDENTIFIERS
    + JURDICARY_IDENTIFIERS
    + ARMED_FORCES_IDENTIFIERS
    + GOVERNMENT_IDENTIFIERS
)

# non constitutional identifiers
CHARITY_IDENTIFIERS = [
    "charity",
    "charitable",
    "foundation",
]

EDUCATION_IDENTIFIERS = [
    "college",
    "school",
    "secondary",
    "primary",
    "academy",
    "trust",
]

HEALTH_IDENTIFIERS = ["hospital", "health", "healthcare"]

COMPANY_IDENTIFIERS = ["company", "limited", "ltd", "plc"]

UNIVERSITY_IDENTIFIERS = [
    "college",
    "university",
]

MISC_IDENTIFIERS = [
    "Fund",
    "Trust",
    "blind trust",
    "association",
    "society",
    "club",
]
